services:
  - type: web
    name: usehub
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -c "from app import create_app; create_app()"
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: MIGRATION_SECRET
        generateValue: true
    plan: free
